name = "SymbolicQuartetCF"
uuid = "bdb2d313-ae54-487a-ba87-13d2dbade7fa"
version = "0.1.4"
authors = ["Sungsik Kong <sungsik.kong@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileCmp = "343a5541-a696-4ae7-8102-bc61c09e1896"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10"
DataFrames = "0.13, 0.14, 0.15, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5"
FileCmp = "1"
PhyloNetworks = "1.2, 1.3"
StaticArrays = "0.9, 0.10, 1.0, 1.1"
julia = "1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13"